# Generated by Django 4.1.7 on 2023-05-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_employer',
            field=models.TextField(blank=True),
        ),
    ]
